db: rethinkdb --bind all
redis: redis-server
web: gunicorn routes:app --reload -b 127.0.0.1:8000 -w 4
change_feed: python -u change_feed.py
worker: python -u worker.py -c 5
clock: python -u clock.py 
splash: python -m splash.server --port=8950
rq_dashboard: rq-dashboard
