class PressClassification:
    def _industries(self):
        return {'Advertising': 'Advertising',
         'Aerospace': 'Aerospace and Defense',
         'Aerospace / Defense': 'Aerospace and Defense',
         'Aerospace News': 'Aerospace and Defense',
         'Aerospace and Defense': 'Aerospace and Defense',
         'Agriculture': 'Agriculture ',
         'Agriculture ': 'Agriculture ',
         'Airlines/Aviation': 'Aerospace and Defense',
         'Alternative Energy': 'Energy and Utilities ',
         'Alternative Vehicles/Fuels': 'Automotive ',
         'Art': 'Lifestyle and Leisure ',
         'Auto & Transportation ': 'Automotive ',
         'Auto Industry': 'Automotive ',
         'Automotive ': 'Automotive ',
         'Automotive Manufacturing': 'Automotive ',
         'Automotive News': 'Automotive ',
         'Banking': 'Financial Services ',
         'Banking/Financial Services': 'Financial Services ',
         'Basketball': 'Sports ',
         'Biotechnology': 'Pharmaceuticals and Biotech ',
         'Business Technology ': 'Electronics and Semiconductors ',
         'Chemical ': 'Chemicals',
         'Chemicals': 'Chemicals',
         'Chemicals/Plastics': 'Chemicals',
         'Coal': 'Manufacturing and Production ',
         'Commercial Building & Real Estate': 'Real Estate and Construction ',
         'Computer Hardware ': 'Electronics and Semiconductors ',
         'Computer Networks ': 'Electronics and Semiconductors ',
         'Computer Software ': 'Computers and Software ',
         'Computers and Software ': 'Computers and Software ',
         'Computers/Electronics': 'Electronics and Semiconductors ',
         'Construction & Property News': 'Real Estate and Construction ',
         'Construction / Building': 'Manufacturing and Production ',
         'Construction/Building ': 'Transportation and Logistics ',
         'Consumer Electronics': 'Electronics and Semiconductors ',
         'Consumer Electronics ': 'Electronics and Semiconductors ',
         'Consumer Products & Retail ': 'Retail ',
         'Corporate Social Responsibility News': 'Education and Training ',
         'Defense News': 'Aerospace and Defense',
         'E-Commerce ': 'Retail ',
         'Electrical': 'Electronics and Semiconductors ',
         'Electronic Components ': 'Electronics and Semiconductors ',
         'Electronic Design ': 'Electronics and Semiconductors ',
         'Electronic Design Automation': 'Electronics and Semiconductors ',
         'Electronic Testers ': 'Electronics and Semiconductors ',
         'Electronics and Semiconductors ': 'Electronics and Semiconductors ',
         'Energy ': 'Energy and Utilities ',
         'Energy & Oil': 'Energy and Utilities ',
         'Energy News': 'Energy and Utilities ',
         'Energy and Utilities ': 'Energy and Utilities ',
         'Entertainment ': 'Media and Entertainment ',
         'Entertainment & Media ': 'Lifestyle and Leisure ',
         'Entertainment News': 'Lifestyle and Leisure ',
         'Environment ': 'Environment ',
         'Environment News': 'Environment ',
         'Environmental Services ': 'Environment ',
         'Fashion': 'Lifestyle and Leisure ',
         'Fashion ': 'Lifestyle and Leisure ',
         'Film ': 'Lifestyle and Leisure ',
         'Films & Motion Pictures': 'Media and Entertainment ',
         'Finance': 'Financial Services ',
         'Financial Services ': 'Financial Services ',
         'Fitness & Nutrition': 'Food and Beverage ',
         'Fleet Management': 'Transportation and Logistics ',
         'Food and Beverage ': 'Lifestyle and Leisure ',
         'Forest Products': 'Manufacturing and Production ',
         'Gambling/Casinos ': 'Lifestyle and Leisure ',
         'Government ': 'Government ',
         'Hardware': 'Electronics and Semiconductors ',
         'Health Care/Hospitals ': 'Medical and Healthcare ',
         'Health News': 'Lifestyle and Leisure ',
         'Healthcare': 'Medical and Healthcare ',
         'Heavy Industry & Manufacturing ': 'Manufacturing and Production ',
         'Home Goods': 'Lifestyle and Leisure ',
         'Hospitals': 'Medical and Healthcare ',
         'Household/Consumer/Cosmetics ': 'Lifestyle and Leisure ',
         'Human Resources': 'Union and Labour ',
         'Hunting': 'Transportation and Logistics ',
         'Infectious Diseases': 'Medical and Healthcare ',
         'Insurance': 'Professional Services ',
         'Insurance ': 'Financial Services ',
         'Internet': 'Electronics and Semiconductors ',
         'Internet Technology ': 'Telecom ',
         'Labor': 'Professional Services ',
         'Leisure': 'Lifestyle and Leisure ',
         'Lifestyle and Leisure ': 'Lifestyle and Leisure ',
         'Logistics': 'Transportation and Logistics ',
         'Logistics / Shipping': 'Transportation and Logistics ',
         'Luxury': 'Lifestyle and Leisure ',
         'Machinery ': 'Manufacturing and Production ',
         'Manufacturing / Production': 'Manufacturing and Production ',
         'Manufacturing News': 'Manufacturing and Production ',
         'Manufacturing and Production ': 'Manufacturing and Production ',
         'Maritime/Ship Building ': 'Manufacturing and Production ',
         'Media and Entertainment ': 'Media and Entertainment ',
         'Medical Devices': 'Electronics and Semiconductors ',
         'Medical Supplies': 'Medical and Healthcare ',
         'Medical and Healthcare ': 'Medical and Healthcare ',
         'Medical/Pharmaceutical': 'Pharmaceuticals and Biotech ',
         'Mining / Metals': 'Manufacturing and Production ',
         'Mining/Metals ': 'Transportation and Logistics ',
         'Mining/Minerals': 'Manufacturing and Production ',
         'Mobile Entertainment': 'Media and Entertainment ',
         'Mobile/Wireless': 'Electronics and Semiconductors ',
         'Motor Sports': 'Automotive ',
         'Motorcycles': 'Automotive ',
         'Multimedia News': 'Media and Entertainment ',
         'Multimedia/Internet/Online Services ': 'Electronics and Semiconductors ',
         'Mutual Funds ': 'Financial Services ',
         'Nanotechnology': 'Electronics and Semiconductors ',
         'Natural Resources News': 'Manufacturing and Production ',
         'Network Security ': 'Electronics and Semiconductors ',
         'Networks': 'Electronics and Semiconductors ',
         'Non-profit': 'Lifestyle and Leisure ',
         'Nuclear': 'Energy and Utilities ',
         'Nursing': 'Medical and Healthcare ',
         'Off-Road Trucks & SUVs': 'Automotive ',
         'Oil / Energy': 'Energy and Utilities ',
         'Oil/Energy': 'Energy and Utilities ',
         'Oil/Gas': 'Manufacturing and Production ',
         'Online': 'Electronics and Semiconductors ',
         'Online Retail': 'Retail ',
         'Optical': 'Medical and Healthcare ',
         'Packaging': 'Manufacturing and Production ',
         'Paper / Forest Products': 'Manufacturing and Production ',
         'Paper/Forest Products ': 'Pharmaceuticals and Biotech ',
         'Pets': 'Lifestyle and Leisure ',
         'Pharmaceutical': 'Pharmaceuticals and Biotech ',
         'Pharmaceuticals and Biotech ': 'Pharmaceuticals and Biotech ',
         'Powerboating': 'Automotive ',
         'Precious Metals ': 'Manufacturing and Production ',
         'Professional Services ': 'Professional Services ',
         'Professional Services News': 'Professional Services ',
         'Public Policy': 'Government ',
         'Public Policy/Government News': 'Government ',
         'Public Transportation': 'Transportation and Logistics ',
         'Public Utilities': 'Energy and Utilities ',
         'Publishing/Informational Services ': 'Media and Entertainment ',
         'REIT': 'Real Estate and Construction ',
         'Radio ': 'Electronics and Semiconductors ',
         'Radiology': 'Pharmaceuticals and Biotech ',
         'Rail': 'Transportation and Logistics ',
         'Real Estate ': 'Real Estate and Construction ',
         'Real Estate and Construction ': 'Real Estate and Construction ',
         'Recreational Vehicles': 'Automotive ',
         'Residential Building & Real Estate': 'Real Estate and Construction ',
         'Restaurant/Bar': 'Food and Beverage ',
         'Retail ': 'Retail ',
         'Retail News': 'Retail ',
         'Retail Reports': 'Retail ',
         'Satellite': 'Electronics and Semiconductors ',
         'Search Engine Marketing': 'Advertising',
         'Search Engine Optimization': 'Advertising',
         'Security': 'Electronics and Semiconductors ',
         'Semiconductor': 'Electronics and Semiconductors ',
         'Semiconductors ': 'Electronics and Semiconductors ',
         'Social Media': 'Lifestyle and Leisure ',
         'Software': 'Computers and Software ',
         'Supermarket': 'Manufacturing and Production ',
         'Supermarkets ': 'Retail ',
         'Supply Chain Management': 'Transportation and Logistics ',
         'TV and Radio': 'Electronics and Semiconductors ',
         'Technology News': 'Electronics and Semiconductors ',
         'Telecom': 'Telecom ',
         'Telecom ': 'Telecom ',
         'Telecommunications': 'Electronics and Semiconductors ',
         'Telecommunications ': 'Telecom ',
         'Television ': 'Electronics and Semiconductors ',
         'Textiles/Apparel ': 'Manufacturing and Production ',
         'Transport News': 'Transportation and Logistics ',
         'Transportation': 'Transportation and Logistics ',
         'Transportation and Logistics ': 'Transportation and Logistics ',
         'Transportation/Trucking/Railroads ': 'Transportation and Logistics ',
         'Travel News': 'Travel and Hospitality ',
         'Travel and Hospitality ': 'Travel and Hospitality ',
         'Trucking': 'Transportation and Logistics ',
         'Union and Labour ': 'Union and Labour ',
         'Venture Capital': 'Financial Services ',
         'Veterinary': 'Lifestyle and Leisure ',
         'White House/Federal Government': 'Government ',
         'Yachting': 'Automotive '}
  
    def _subjects(self):
        return {'Award News': 'Awards & Certifications',
         'Awards': 'Awards & Certifications',
         'Bankruptcies': 'Litigations',
         'Bankruptcy': 'Business Challenges',
         'Bankruptcy News': 'Business Challenges',
         'Class Action': 'Business Challenges',
         'Conference Calls': 'Litigations',
         'Consumer Research': 'New Offerings',
         'Contest News': 'Awards & Certifications',
         'Contract/Agreements News': 'New Contracts',
         'Corporate Social Responsibility News': 'Awards & Certifications',
         'Dividend News': 'Litigations',
         'Earnings': 'Revenue & Earnings',
         'Earnings    Forecast Projects': 'Revenue & Earnings',
         'Earnings Forecasts': 'Revenue & Earnings',
         'Earnings News': 'Revenue & Earnings',
         'Employment': 'Personnel Changes',
         'Executives': 'Personnel Changes',
         'Feature News': 'New Offerings',
         'Filing News': 'Growth & Expansion',
         'Finance': 'Business Challenges',
         'Financial Agreements': 'Business Challenges',
         'Financing Agreements': 'Growth & Expansion',
         'Franchise': 'New Offerings',
         'Funding News': 'Growth & Expansion',
         'Funds': 'Business Challenges',
         'Human Resources': 'Personnel Changes',
         'IPO News': 'Growth & Expansion',
         'Initial Public Offerings (IPOs)': 'Growth & Expansion',
         'Investment': 'Funding & Development',
         'Joint Ventures': 'Mergers & Acquisitions',
         'Lawsuit News': 'Business Challenges',
         'Legal': 'Litigations',
         'Licensing Agreements': 'Growth & Expansion',
         'Management': 'Personnel Changes',
         'Management Changes': 'Personnel Changes',
         'Merger/Acquisition News': 'Mergers & Acquisitions',
         'Mergers    and Aqc.': 'Mergers & Acquisitions',
         'Mergers and Acquisitions': 'Mergers & Acquisitions',
         'Mutual Fund News': 'Litigations',
         'Natural Resource Discoveries': 'Business Challenges',
         'New Products/Services': 'New Offerings',
         'Offerings': 'New Offerings',
         'Personnel Announcements': 'Personnel Changes',
         'Personnel News': 'Personnel Changes',
         'Private Equity': 'Funding & Development',
         'Private Placement': 'Funding & Development',
         'Products & Services News': 'New Offerings',
         'Real Estate': 'Real Estate Transactions',
         'Real Estate Transactions': 'Real Estate Transactions',
         'Restructuring': 'Business Challenges',
         'Sales News': 'New Contracts',
         'Share Issue News': 'Business Challenges',
         'Shareholders Rights Plans': 'Business Challenges',
         'Special News Events': 'Business Challenges',
         'Stock Split News': 'Business Challenges',
         'Stock Splits': 'Litigations',
         'Stock/Other Market News': 'Revenue & Earnings',
         'Surveys': 'New Offerings',
         'Trade Shows': 'New Offerings',
         'Trade Shows News': 'New Offerings',
         'Trade Shows/Seminars': 'New Offerings',
         'Venture Capital': 'Growth & Expansion',
         'e-Commerce': 'New Offerings'}

